// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_stage9 = "CgkIu8CaxfkWEAIQHg"; // <GPGSID>
        public const string leaderboard_stage6h = "CgkIu8CaxfkWEAIQEA"; // <GPGSID>
        public const string leaderboard_stage7 = "CgkIu8CaxfkWEAIQHA"; // <GPGSID>
        public const string leaderboard_stage1h = "CgkIu8CaxfkWEAIQCw"; // <GPGSID>
        public const string leaderboard_stage2h = "CgkIu8CaxfkWEAIQDA"; // <GPGSID>
        public const string leaderboard_stage4 = "CgkIu8CaxfkWEAIQGQ"; // <GPGSID>
        public const string leaderboard_stage8h = "CgkIu8CaxfkWEAIQEg"; // <GPGSID>
        public const string leaderboard_stage5h = "CgkIu8CaxfkWEAIQDw"; // <GPGSID>
        public const string leaderboard_stage1 = "CgkIu8CaxfkWEAIQFg"; // <GPGSID>
        public const string leaderboard_stage2 = "CgkIu8CaxfkWEAIQFw"; // <GPGSID>
        public const string leaderboard_stage10 = "CgkIu8CaxfkWEAIQHw"; // <GPGSID>
        public const string leaderboard_stage3h = "CgkIu8CaxfkWEAIQDQ"; // <GPGSID>
        public const string leaderboard_stage6 = "CgkIu8CaxfkWEAIQGw"; // <GPGSID>
        public const string leaderboard_stage8 = "CgkIu8CaxfkWEAIQHQ"; // <GPGSID>
        public const string leaderboard_stage7h = "CgkIu8CaxfkWEAIQEQ"; // <GPGSID>
        public const string leaderboard_stage5 = "CgkIu8CaxfkWEAIQGg"; // <GPGSID>
        public const string leaderboard_stage9h = "CgkIu8CaxfkWEAIQEw"; // <GPGSID>
        public const string leaderboard_stage10h = "CgkIu8CaxfkWEAIQFA"; // <GPGSID>
        public const string leaderboard_stage3 = "CgkIu8CaxfkWEAIQGA"; // <GPGSID>
        public const string leaderboard_stage4h = "CgkIu8CaxfkWEAIQDg"; // <GPGSID>

}

